# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Zig Shellcode Runner Example
# Copyright (C) 2025 Ivan Stepanov <ivanstepanovftw@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: CI

on:
  push:
    branches: ["main", "ci"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: ""

      - name: Check formatting
        run: zig fmt --check .

      - name: Build
        run: zig build --release=safe

      - name: Test
        run: |
          output=$( (echo 'hi' | ./zig-out/bin/runner) 2>&1 || true )
          echo "$output"
          echo "$output" | grep -q "/bin/sh: 1: hi: not found"

  release:
    name: Create GitHub Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: lint_and_test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ""

      - name: Build release binary
        run: zig build --release=fast

      - name: Prepare release asset
        run: |
          mv ./zig-out/bin/runner ./runner-${{ github.ref_name }}-linux-x86_64

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: ./runner-${{ github.ref_name }}-linux-x86_64
